package com.asynchrony.nlp.classifier;

public class TrainingSet {
	
	public static final String UNKNOWN = "Unknown";
	public static final String TRAINING_CATEGORIES[][] = 
		{{"-1", UNKNOWN}, {"0", UNKNOWN}, 
		{"1", "Thinking Strategically"}, {"2", "Determination"}, 
		{"3", "Composed"}, {"4", "Visualization"}, {"5", "Problems Perceiving Them"},
		{"6", "Creativity"}, {"7", "Integrity"}, {"8", "Motivating Others"}};
	
	
	public static final String TRAINING_SET_PHRASES[][] = 
		{{"4", "0.2", "Dan explained a user-driven approach to visualization and modeling."},
		{"4", "0.2", "When visualizing the ideal plan, John was right there."},
		{"4", "0.2", "Wes was eager to demonstrate incorporating visualization into a successful routine."},
		{"4", "0.2", "Visualization of the required work was daunting until Ryan stepped to the podium."},
		{"4", "0.2", "Edward wisely used to time to teach the team techniques in visualization."},
		{"4", "0.2", "Greg is able to visualize the ideal of everything that he would like to achieve."},
		{"4", "0.2", "Andi is able to visualize and analyze both basic and creative solutions."},
		{"4", "0.2", "Visualization and planning explain the success of this project."},
		{"4", "0.2", "Wilbert showed the team how visualization can help bring about remarkable change."},
		{"4", "0.2", "James does all the right things; he visualizes and expresses gratitude."},
		{"2", "0.8", "Thanks to Dave, the draft determination will protect customers from significant price shocks."},
		{"2", "0.8", "In understanding the clients issues, Ben's determination never wavered."},
		{"2", "0.8", "The overriding reason we landed the contract was Neil's determination to please the client."},
		{"2", "0.8", "Next time you are tired or second guessing yourself, try to channel your determination."},
		{"2", "0.8", "The determination in John is incredible, he never gives up."},
		{"2", "0.8", "He has the ability to see past the challenge with his determination."},
		{"2", "0.8", "Nathan returned to school with a determination to finish."},
		{"2", "0.8", "As usual, Lisa approached the task with determination and energy."},
		{"2", "0.8", "William's determination carried him through the battle."},
		{"2", "0.8", "We learned quickly that the most important predictor of success is determination."},
		{"2", "0.8", "Bob's determination would not allow him to leave the office until the task was completed."},
		{"2", "0.8", "Through perseverance and determination, Jason ensured the project would be a success."},
		{"2", "0.8", "Joe displayed a fierce determination not to accept defeat."},
		{"1", "0.7", "Lee was thinking strategically when he organized our new digital Kanban board."},
		{"1", "0.7", "During our retrospective, the entire team was thinking strategically in moving our standups to the phone system."},
		{"1", "0.7", "The team lead, thinking strategically, brought healthy breakfast selections to our early morning meeting."},
		{"1", "0.7", "By keeping our technology options open, Travis was thinking strategically."},
		{"1", "0.7", "By bringing her lunch to work, Mackenzie was thinking strategically about organizing her day."},
		{"1", "0.7", "Thinking strategically, Nate exchanged team developers on an individual basis."},
		{"1", "0.7", "Ryan was thinking strategically when he took the initiative to learn a new technology."},
		{"1", "0.7", "The team created a branching policy by thinking strategically."},
		{"1", "0.7", "Steve was thinking strategically by suggesting the use of natural language processing."},
		{"1", "0.7", "The dog was thinking strategically when he buried his extra bone in the back yard."},
		{"1", "0.7", "Robert's decision to include documentation showed that he was thinking strategically."},
		{"1", "0.7", "Jason's role is to ensure that the team is thinking strategically."},
		{"1", "0.7", "The fate of the project was announced, showing he was thinking strategically."},
		{"1", "0.7", "The presentation included strategically positioned highlights."},
		{"3", "0.5", "Lee remained composed as the remote developers became upset."},
		{"3", "0.5", "Sara maintained her composure as the client criticized her presentation."},
		{"3", "0.5", "Although the room became heated, Bob remain completely composed."},
		{"3", "0.5", "Composure was maintained by all as the bad news was delivered."},
		{"3", "0.5", "June retained her composure after the non politically correct joke."},
		{"3", "0.5", "Unsurprisingly, Sherri did not maintain her composure."},
		{"3", "0.5", "As the bad news was delivered, everyone except Missi maintained their composure."},
		{"3", "0.5", "Mark was as composed as a church mouse when he lost the game."},
		{"3", "0.5", "I was surprised that Sarah did not remain composed after she was fired."},
		{"3", "0.5", "Remaining composed was the focus of the motivational speaker."},
		{"3", "0.5", "He accepted their problems with composure and she with equanimity."}, 
		{"5", "0.9", "Mike quickly saw the problem with the project"},
		{"5", "0.9", "John did a good job at determining that the system was not performing correctly"},
		{"5", "0.9", "Lacy perceived that there were problems that were not being addressed"},
		{"5", "0.9", "Barb was able to see that the machine was broken"},
		{"5", "0.9", "William saw that the dependencies were not aligned correctly"},
		{"5", "0.9", "Dave became aware of the problems that were plaguing the installation"},
		{"5", "0.9", "Jess realized that the inefficiency was due to the machine design"},
		{"5", "0.9", "Steve discerned that the team was failing to perform well enough"},
		{"5", "0.9", "Greg identified that there was no responsible party identified"},
		{"5", "0.9", "Geena comprehended that the nature of the problem was machine based"},
		{"5", "0.9", "Chevy understood that there were too many steps in the process"},
		{"6", "0.6", "Mary came up with a unique solution to the problem"},
		{"6", "0.6", "David was thinking out of the box when he solved the issue"},
		{"6", "0.6", "Susan came up with a creative process to fix the machine"},
		{"6", "0.6", "Thomas thought of an inventive solution"},
		{"6", "0.6", "Harry was really resourceful in his quick response to the work overflow"},
		{"6", "0.6", "The way that Donald came up with the design was inspired"},
		{"6", "0.6", "Holly's decision to use excel to determine the cause of the issue was creative"},
		{"6", "0.6", "Sammy creatively designed the updated machine"},
		{"7", "0.4", "Milton showed great integrity when he turned down the untoward offer"},
		{"7", "0.4", "Harry honestly explained the truth of the situation"},
		{"7", "0.4", "Martin acted honorably when deailng with the situation"},
		{"7", "0.4", "Sally's proposal showed honesty in understanding her own weaknesses"},
		{"7", "0.4", "Harold was sincere in his description of his beliefs"},
		{"7", "0.4", "Mary was virtuous in her attempts to describe the situation"},
		{"7", "0.4", "Phil acted with integrity"},
		{"7", "0.4", "Steve showed integrity when he resigned from the position"},
		{"8", "0.8", "Michael failed to motivate his team"},
		{"8", "0.8", "David lead his project team successfully"},
		{"8", "0.8", "Thomas inspired his group to complete the project on time"},
		{"8", "0.8", "Shelly spurred on the members to greater success"},
		{"8", "0.8", "Susan motivated her team well"},
		{"8", "0.8", "Brian was unable to motivate the team"},
		{"8", "0.8", "The failure of Sally to provide motivation for the effort was why the project failed"},
		{"8", "0.8", "Lilly was inspiring during the discussions"},
		{"8", "0.8", "Phil couldn't motivate his project team"}
		};

}
